/* content from:
 * http://marijn.haverbeke.nl/codemirror/js/codemirror.js
 * closure compiled 2010-07-08 */
var CodeMirrorConfig=window.CodeMirrorConfig||{},CodeMirror=function(){function B(a,b){for(var c in b)a.hasOwnProperty(c)||(a[c]=b[c])}function C(a,b){for(var c=0;c<a.length;c++)b(a[c])}function D(a){var b=document.createElement("DIV"),c=document.createElement("DIV");b.style.position="absolute";b.style.height="100%";if(b.style.setExpression)try{b.style.setExpression("height","this.previousSibling.offsetHeight + 'px'")}catch(f){}b.style.top="0px";b.style.left="0px";b.style.overflow="hidden";a.appendChild(b);
c.className="CodeMirror-line-numbers";b.appendChild(c);c.innerHTML="<div>1</div>";return b}function E(a){if(typeof a.parserfile=="string")a.parserfile=[a.parserfile];if(typeof a.stylesheet=="string")a.stylesheet=[a.stylesheet];var b=['<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head>'];b.push('<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>');C(a.stylesheet,function(c){b.push('<link rel="stylesheet" type="text/css" href="'+
c+'"/>')});C(a.basefiles.concat(a.parserfile),function(c){/^https?:/.test(c)||(c=a.path+c);b.push('<script type="text/javascript" src="'+c+'"><\/script>')});b.push('</head><body style="border-width: 0;" class="editbox" spellcheck="'+(a.disableSpellcheck?"false":"true")+'"></body></html>');return b.join("")}function q(a,b){this.options=b=b||{};B(b,CodeMirrorConfig);if(b.dumbTabs)b.tabMode="spaces";else if(b.normalTab)b.tabMode="default";var c=this.frame=document.createElement("IFRAME");if(b.iframeClass)c.className=
b.iframeClass;c.frameBorder=0;c.style.border="0";c.style.width="100%";c.style.height="100%";c.style.display="block";var f=this.wrapping=document.createElement("DIV");f.style.position="relative";f.className="CodeMirror-wrapping";f.style.width=b.width;f.style.height=b.height;var g=this.textareaHack=document.createElement("TEXTAREA");f.appendChild(g);g.style.position="absolute";g.style.left="-10000px";g.style.width="10px";c.CodeMirror=this;if(b.domain&&F){this.html=E(b);c.src="javascript:(function(){document.open();"+
(b.domain?'document.domain="'+b.domain+'";':"")+"document.write(window.frameElement.CodeMirror.html);document.close();})()"}else c.src="javascript:false";a.appendChild?a.appendChild(f):a(f);f.appendChild(c);if(b.lineNumbers)this.lineNumbers=D(f);this.win=c.contentWindow;if(!b.domain||!F){this.win.document.open();this.win.document.write(E(b));this.win.document.close()}}B(CodeMirrorConfig,{stylesheet:[],path:"",parserfile:[],basefiles:["util.js","stringstream.js","select.js","undo.js","editor.js","tokenize.js"],
iframeClass:null,passDelay:200,passTime:50,lineNumberDelay:200,lineNumberTime:50,continuousScanning:false,saveFunction:null,onChange:null,undoDepth:50,undoDelay:800,disableSpellcheck:true,textWrapping:true,readOnly:false,width:"",height:"300px",autoMatchParens:false,parserConfig:null,tabMode:"indent",reindentOnLoad:false,activeTokens:null,cursorActivity:null,lineNumbers:false,indentUnit:2,domain:null});var F=document.selection&&window.ActiveXObject&&/MSIE/.test(navigator.userAgent);q.prototype={init:function(){this.options.initCallback&&
this.options.initCallback(this);this.options.lineNumbers&&this.activateLineNumbers();this.options.reindentOnLoad&&this.reindent()},getCode:function(){return this.editor.getCode()},setCode:function(a){this.editor.importCode(a)},selection:function(){this.focusIfIE();return this.editor.selectedText()},reindent:function(){this.editor.reindent()},reindentSelection:function(){this.focusIfIE();this.editor.reindentSelection(null)},focusIfIE:function(){this.win.select.ie_selection&&this.focus()},focus:function(){this.win.focus();
this.editor.selectionSnapshot&&this.win.select.setBookmark(this.win.document.body,this.editor.selectionSnapshot)},replaceSelection:function(a){this.focus();this.editor.replaceSelection(a);return true},replaceChars:function(a,b,c){this.editor.replaceChars(a,b,c)},getSearchCursor:function(a,b,c){return this.editor.getSearchCursor(a,b,c)},undo:function(){this.editor.history.undo()},redo:function(){this.editor.history.redo()},historySize:function(){return this.editor.history.historySize()},clearHistory:function(){this.editor.history.clear()},
grabKeys:function(a,b){this.editor.grabKeys(a,b)},ungrabKeys:function(){this.editor.ungrabKeys()},setParser:function(a,b){this.editor.setParser(a,b)},setSpellcheck:function(a){this.win.document.body.spellcheck=a},setStylesheet:function(a){if(typeof a==="string")a=[a];for(var b={},c={},f=this.win.document.getElementsByTagName("link"),g=0,d;d=f[g];g++)if(d.rel.indexOf("stylesheet")!==-1)for(var e=0;e<a.length;e++){var l=a[e];if(d.href.substring(d.href.length-l.length)===l){b[d.href]=true;c[l]=true}}for(g=
0;d=f[g];g++)if(d.rel.indexOf("stylesheet")!==-1)d.disabled=!(d.href in b);for(e=0;e<a.length;e++){l=a[e];if(!(l in c)){d=this.win.document.createElement("link");d.rel="stylesheet";d.type="text/css";d.href=l;this.win.document.getElementsByTagName("head")[0].appendChild(d)}}},setTextWrapping:function(a){if(a!=this.options.textWrapping){this.win.document.body.style.whiteSpace=a?"":"nowrap";this.options.textWrapping=a;if(this.lineNumbers){this.setLineNumbers(false);this.setLineNumbers(true)}}},setIndentUnit:function(a){this.win.indentUnit=
a},setUndoDepth:function(a){this.editor.history.maxDepth=a},setTabMode:function(a){this.options.tabMode=a},setLineNumbers:function(a){if(a&&!this.lineNumbers){this.lineNumbers=D(this.wrapping);this.activateLineNumbers()}else if(!a&&this.lineNumbers){this.wrapping.removeChild(this.lineNumbers);this.wrapping.style.marginLeft="";this.lineNumbers=null}},cursorPosition:function(a){this.focusIfIE();return this.editor.cursorPosition(a)},firstLine:function(){return this.editor.firstLine()},lastLine:function(){return this.editor.lastLine()},
nextLine:function(a){return this.editor.nextLine(a)},prevLine:function(a){return this.editor.prevLine(a)},lineContent:function(a){return this.editor.lineContent(a)},setLineContent:function(a,b){this.editor.setLineContent(a,b)},removeLine:function(a){this.editor.removeLine(a)},insertIntoLine:function(a,b,c){this.editor.insertIntoLine(a,b,c)},selectLines:function(a,b,c,f){this.win.focus();this.editor.selectLines(a,b,c,f)},nthLine:function(a){for(var b=this.firstLine();a>1&&b!==false;a--)b=this.nextLine(b);
return b},lineNumber:function(a){for(var b=0;a!==false;){b++;a=this.prevLine(a)}return b},jumpToLine:function(a){if(typeof a=="number")a=this.nthLine(a);this.selectLines(a,0);this.win.focus()},currentLine:function(){return this.lineNumber(this.cursorLine())},cursorLine:function(){return this.cursorPosition().line},cursorCoords:function(a){return this.editor.cursorCoords(a)},activateLineNumbers:function(){function a(){if(d.offsetWidth!=0){for(var h=d;h.parentNode;h=h.parentNode);if(!t.parentNode||
h!=document||!e.Editor){try{x()}catch(k){}clearInterval(I)}else if(t.offsetWidth!=y){y=t.offsetWidth;d.parentNode.style.paddingLeft=y+"px"}}}function b(){t.scrollTop=v.scrollTop||l.documentElement.scrollTop||0}function c(h){var k=o.firstChild.offsetHeight;if(k!=0){k=Math.ceil((50+Math.max(v.offsetHeight,Math.max(d.offsetHeight,v.scrollHeight||0)))/k);for(var p=o.childNodes.length;p<=k;p++){var u=document.createElement("DIV");u.appendChild(document.createTextNode(h?String(p+1):"\u00a0"));o.appendChild(u)}}}
function f(){function h(){c(true);b()}j.updateNumbers=h;var k=e.addEventHandler(e,"scroll",b,true),p=e.addEventHandler(e,"resize",h,true);x=function(){k();p();if(j.updateNumbers==h)j.updateNumbers=null};h()}function g(){function h(m,z){n||(n=o.appendChild(document.createElement("DIV")));G&&G(n,z,m);r.push(n);r.push(m);A=n.offsetHeight+n.offsetTop;n=n.nextSibling}function k(){for(var m=0;m<r.length;m+=2)r[m].innerHTML=r[m+1];r=[]}function p(){if(!(!o.parentNode||o.parentNode!=j.lineNumbers)){for(var m=
(new Date).getTime()+j.options.lineNumberTime;i;){for(h(H++,i.previousSibling);i&&!e.isBR(i);i=i.nextSibling)for(var z=i.offsetTop+i.offsetHeight;o.offsetHeight&&z-3>A;)h("&nbsp;");if(i)i=i.nextSibling;if((new Date).getTime()>m){k();s=setTimeout(p,j.options.lineNumberDelay);return}}k();b()}}function u(){b();c(false);i=v.firstChild;n=o.firstChild;A=0;H=1;p()}function w(){s&&clearTimeout(s);if(j.editor.allClean())u();else s=setTimeout(w,200)}var i,n,H,A,r=[],G=j.options.styleNumbers;u();var s=null;
j.updateNumbers=w;var J=e.addEventHandler(e,"scroll",b,true),K=e.addEventHandler(e,"resize",w,true);x=function(){s&&clearTimeout(s);if(j.updateNumbers==w)j.updateNumbers=null;J();K()}}var d=this.frame,e=d.contentWindow,l=e.document,v=l.body,t=this.lineNumbers,o=t.firstChild,j=this,y=null,x=function(){};a();var I=setInterval(a,500);(this.options.textWrapping||this.options.styleNumbers?g:f)()}};q.InvalidLineHandle={toString:function(){return"CodeMirror.InvalidLineHandle"}};q.replace=function(a){if(typeof a==
"string")a=document.getElementById(a);return function(b){a.parentNode.replaceChild(b,a)}};q.fromTextArea=function(a,b){if(typeof a=="string")a=document.getElementById(a);b=b||{};if(a.style.width&&b.width==null)b.width=a.style.width;if(a.style.height&&b.height==null)b.height=a.style.height;if(b.content==null)b.content=a.value;if(a.form){var c=function(){a.value=d.getCode()};typeof a.form.addEventListener=="function"?a.form.addEventListener("submit",c,false):a.form.attachEvent("onsubmit",c);var f=a.form.submit,
g=function(){c();a.form.submit=f;a.form.submit();a.form.submit=g};a.form.submit=g}a.style.display="none";var d=new q(function(e){a.nextSibling?a.parentNode.insertBefore(e,a.nextSibling):a.parentNode.appendChild(e)},b);return d};q.isProbablySupported=function(){var a;return window.opera?Number(window.opera.version())>=9.52:/Apple Computers, Inc/.test(navigator.vendor)&&(a=navigator.userAgent.match(/Version\/(\d+(?:\.\d+)?)\./))?Number(a[1])>=3:document.selection&&window.ActiveXObject&&(a=navigator.userAgent.match(/MSIE (\d+(?:\.\d*)?)\b/))?
Number(a[1])>=6:(a=navigator.userAgent.match(/gecko\/(\d{8})/i))?Number(a[1])>=20050901:(a=navigator.userAgent.match(/AppleWebKit\/(\d+)/))?Number(a[1])>=525:null};return q}();