/* content from:
 * http://marijn.haverbeke.nl/codemirror/js/parsejavascript.js
 * closure compiled 2010-07-08 */
var JSParser=Editor.Parser=function(){function E(f,n,o,b,h,u){this.indented=f;this.column=n;this.type=o;if(b!=null)this.align=b;this.prev=h;this.info=u}function O(f){return function(n){var o=n&&n.charAt(0),b=f.type,h=o==b;return b=="vardef"?f.indented+4:b=="form"&&o=="{"?f.indented:b=="stat"||b=="form"?f.indented+indentUnit:f.info=="switch"&&!h?f.indented+(/^(?:case|default)\b/.test(n)?indentUnit:2*indentUnit):f.align?f.column-(h?1:0):f.indented+(h?0:indentUnit)}}var F={atom:true,number:true,variable:true,
string:true,regexp:true},G=false;return{make:function(f,n){function o(a){for(var c=a.length-1;c>=0;c--)p.push(a[c])}function b(){o(arguments);v=true}function h(){o(arguments);v=false}function u(){k={prev:k,vars:{"this":true,arguments:true}}}function H(){k=k.prev}function z(a){if(k){r="js-variabledef";k.vars[a]=true}}function g(a,c){var q=function(){j=new E(w,t,a,null,j,c)};q.lex=true;return q}function e(){j=j.prev}function i(a){return function(c){c==a?b():b(arguments.callee)}}function I(){return h(m,
I)}function J(){return h(d,J)}function m(a){if(a=="var")b(g("vardef"),A,i(";"),e);else if(a=="keyword a")b(g("form"),d,m,e);else if(a=="keyword b")b(g("form"),m,e);else if(a=="{")b(g("}"),B,e);else if(a=="function")b(C);else if(a=="for")b(g("form"),i("("),g(")"),P,i(")"),e,m,e);else if(a=="variable")b(g("stat"),Q);else if(a=="switch")b(g("form"),d,g("}","switch"),i("{"),B,e,e);else if(a=="case")b(d,i(":"));else if(a=="default")b(i(":"));else a=="catch"?b(g("form"),u,i("("),K,i(")"),m,e,H):h(g("stat"),
d,i(";"),e)}function d(a){if(F.hasOwnProperty(a))b(l);else if(a=="function")b(C);else if(a=="keyword c")b(d);else if(a=="(")b(g(")"),d,i(")"),e,l);else if(a=="operator")b(d);else if(a=="[")b(g("]"),x(d,"]"),e,l);else a=="{"?b(g("}"),x(R,"}"),e,l):b()}function l(a){if(a=="operator")b(d);else if(a=="(")b(g(")"),d,x(d,")"),e,l);else if(a==".")b(S,l);else a=="["&&b(g("]"),d,i("]"),e,l)}function Q(a){a==":"?b(e,m):h(l,i(";"),e)}function S(a){if(a=="variable"){r="js-property";b()}}function R(a){if(a=="variable")r=
"js-property";F.hasOwnProperty(a)&&b(i(":"),d)}function x(a,c){function q(s){if(s==",")b(a,q);else s==c?b():b(i(c))}return function(s){s==c?b():h(a,q)}}function B(a){a=="}"?b():h(m,B)}function A(a,c){if(a=="variable"){z(c);b(L)}else b()}function L(a,c){if(c=="=")b(d,L);else a==","&&b(A)}function P(a){if(a=="var")b(A,y);else if(a==";")h(y);else a=="variable"?b(T):h(y)}function T(a,c){c=="in"?b(d):b(l,y)}function y(a,c){if(a==";")b(M);else c=="in"?b(d):b(d,i(";"),M)}function M(a){a==")"?h():b(d)}function C(a,
c){if(a=="variable"){z(c);b(C)}else a=="("&&b(u,x(K,")"),m,H)}function K(a,c){if(a=="variable"){z(c);b()}}var D=tokenizeJavaScript(f),p=[G?J:I],k=null,j=new E((n||0)-indentUnit,0,"block",false),t=0,w=0,v,r,N={next:function(){for(;p[p.length-1].lex;)p.pop()();var a=D.next();if(a.type=="whitespace"&&t==0)w=a.value.length;t+=a.value.length;if(a.content=="\n"){w=t=0;if(!("align"in j))j.align=false;a.indentation=O(j)}if(a.type=="whitespace"||a.type=="comment")return a;if(!("align"in j))j.align=true;for(;;){v=
r=false;p.pop()(a.type,a.content);if(v){if(r)a.style=r;else{var c;if(c=a.type=="variable")a:{for(c=k;c;){if(c.vars[a.content]){c=true;break a}c=c.prev}c=false}if(c)a.style="js-localvariable"}return a}}},copy:function(){var a=k,c=j,q=p.concat([]),s=D.state;return function(U){k=a;j=c;p=q.concat([]);t=w=0;D=tokenizeJavaScript(U,s);return N}}};e.lex=true;return N},electricChars:"{}:",configure:function(f){if(f.json!=null)G=f.json}}}();